"""Issue #255 first-loss boundary classification."""

from __future__ import annotations

from collections.abc import Mapping
from typing import Any

SOURCE_NAMES = ("fresh_baseline", "current_sr", "current_omr")


def classify_first_loss_boundary(
    *,
    source_trace: Mapping[str, Mapping[str, Any]],
    probe_trace: Mapping[str, Any],
    cnn_scored: Mapping[str, Any],
    cnn_accepted: Mapping[str, Any],
    accepted_final: bool,
) -> str:
    """Return the earliest unrecovered layer that causes the final absence.

    A target may disappear from hybrid consensus and then be regenerated by the
    raw probe.  In that case the effective loss is the later stage that removes
    the regenerated candidate, not the transient upstream absence.
    """
    if accepted_final:
        return "already_accepted_final"
    if not probe_trace.get("row_bands"):
        return "row_band_construction"
    if probe_trace["raw"]["accepted"]:
        for key, boundary in (
            ("size_filtered", "size_filter"),
            ("heuristic_filtered", "candidate_filter"),
            ("trimmed", "trim"),
            ("final", "probe_final_set"),
        ):
            if not probe_trace[key]["accepted"]:
                return boundary
    else:
        if not any(source_trace[name]["accepted"] for name in SOURCE_NAMES):
            return "absent_from_all_upstream_detectors"
        if not source_trace["hybrid"]["accepted"]:
            return "hybrid_consensus"
        return "raw_probe_generation"
    if not cnn_scored["accepted"]:
        return "cnn_scoring_input"
    if not cnn_accepted["accepted"]:
        return "cnn_filtering"
    return "final_detector_merge"
