/* Controlled English copy for the reviewer application. Keep reviewer wording here. */
window.ReviewStrings = Object.freeze({
  noPageChanges: "No changes for this page and task.",
  clearDecision: "Clear recorded decision",
  result: {
    apply: "Generate corrected PDF", open: "Open corrected PDF",
    running: "Generating corrected PDF…",
    pending: "Record your edits before generating a corrected PDF.",
    stale: "The previous corrected PDF does not include the current corrections.",
    current: "The corrected PDF includes the recorded corrections.",
    ready: "Recorded corrections are ready to apply.",
    failure: "Corrected PDF needs attention", requestFailed: "Generation request failed",
  },
  state: {
    heading: "Correction status", pending: "unsaved", recorded: "recorded", errors: "errors", unavailable: "Correction status unavailable",
    page: "Page", source: "Source", result: "Corrected result",
    types: {mmr_measure_span: "Measure span", measure_construction: "Measure", barline_construction: "Barline", movement_boundary: "Movement boundary"},
  },
  title: "Review correction",
  navigation: "Review result",
  page: "Page",
  previous: "Previous",
  next: "Next",
  selection: "Selected target",
  noSelection: "Select a measure, barline, or system on the score.",
  task: "Correction task",
  taskType: "Correction type",
  types: { mmr_measure_span: "Measure grouping", barline_construction: "Barline", measure_construction: "Measure", movement_boundary: "Movement boundary" },
  measureSpan: "Measure span",
  targetSystem: "Target system",
  reason: "Reason",
  currentChanges: "Current page changes",
  finishMovement: "Finish movement review",
  operation: "Change",
  operations: {
    mmr_measure_span: [["set_measure_span", "Set measure span"], ["suppress", "Remove grouping override"]],
    barline_construction: [["remove_barline", "Remove barline"], ["add_barline", "Add barline"]],
    measure_construction: [["force_measure", "Add measure"]],
    movement_boundary: [["boundary", "Confirm boundary before system"], ["no_boundary", "Confirm no boundary here"]],
  },
  select: "Select target",
  draw: "Draw barline",
  stage: "Add change",
  remove: "Remove change",
  save: "Save changes",
  saved: "Changes saved.",
  noChanges: "There are no unsaved changes.",
  feedback: {
    selectMeasure: "Select a measure on the score first.",
    invalidSpan: "Enter a measure span of 1 or more.",
    draftAdded: "Draft added. Save changes to record it.",
    stagedSpan: "Draft: measure span",
    stagedSuppression: "Draft: grouping removed",
    invalidSystem: "Enter a valid system number.",
    missingSystem: "System {system} is not on this page.",
    noSuggestion: "There is no suggested boundary here to dismiss.",
    savingBoundary: "Saving boundary before system {system}…",
    savingNoBoundary: "Saving no-boundary decision before system {system}…",
    savedBoundary: "Boundary before system {system} saved.",
    savedNoBoundary: "No-boundary decision before system {system} saved.",
    selectBarline: "Select a barline or draw one on the score.",
    selectInterval: "Select a measure interval on the score first.",
    removedDraft: "Draft removed.",
    removingDecision: "Removing saved decision…",
    clearedDecision: "Saved decision removed.",
    pageMovement: "This page: {existing} current boundaries · {confirmed} confirmed · {checked} checked with no boundary · {suggestions} suggestions",
    finishBlocked: "Review the remaining {count} boundary suggestions before finishing.",
    finishMovement: "Movement review finished. {count} confirmed boundaries are ready for the next numbering run.",
    finishMovementFailed: "Could not finish movement review: {error}",
    movementSaveFailed: "Could not save movement decision: {error}",
    saveFailed: "Could not save changes: {error}",
    pageSaveFailed: "Page change stopped because saving failed: {error}",
  },
  status: "Correction status",
  editStatus: "Editing",
  recordingStatus: "Saved changes",
  applicationStatus: "Result status",
  apply: "Apply changes",
  openResult: "Open corrected result",
  details: "Details and evidence",
  display: "Score display",
  measures: "Measures",
  barlines: "Barlines",
  labels: "Labels",
  baseState: "Original grouping",
  manualState: "Your changes",
  movement: "Movement boundaries",
  canvasHint: "Scroll to zoom · Space-drag or middle-drag to pan · ←/→ changes page",
  stateLoading: "Loading correction status…",
  stateUnavailable: "Correction status is not available yet.",
  unsaved: "Changes not saved",
  empty: "No correction selected",
});
