/* Controlled reviewer copy for the English and Japanese application surfaces. */
const reviewEnglish = {
  language: "Language",
  aria: {language: "Language", pages: "Result pages", display: "Score display", canvas: "Score review canvas"},
  ui: {
    change: "Change", page: "Page", system: "System", measure: "Measure", span: "span", bbox: "bbox", draft: "Draft",
    unsaved: "Unsaved", confirmBoundary: "Confirm boundary before system", confirmNoBoundary: "Confirm no boundary here",
    noSystem: "No target system selected. Click inside the intended system or enter its number.",
    movementPrompt: "Choose a system to review its movement boundary.", noSystemSelected: "No system selected.",
    selectedMeasure: "Selected via Measure {measure}; that measure only identifies the system.",
    currentState: "Current state: {state}.", noBoundaryState: "Current state: no suggested or confirmed boundary.",
    targetBefore: "Target: System {system}. A boundary will be placed BEFORE this system.",
    missingSystem: "System {system} is not present on this page.",
    movementCounts: "This page: current-numbering boundaries {existing} · confirmed boundaries {confirmed} · checked no-boundary {checked} · suggestions to review {suggestions}",
    target: "TARGET", before: "before", selectedBarline: "Selected barline", normal: "Normal", baseMmr: "Base MMR",
    noMeasures: "No measure boxes loaded from the numbering artifact.", movementGuide: "All locations below mean BEFORE System N. Click a row to target that system on the score.",
    confirmedBoundary: "confirmed boundary", manualBoundary: "confirmed boundary (manual)", checkedNoBoundary: "checked: no boundary",
    resolvedBoundary: "boundary used by current numbering · reset={reset}", suggestedBoundary: "suggested boundary — needs review",
    beforeSystem: "BEFORE System {system} · {state}", detectionDetails: "Detection details",
    noBoundaryRows: "No suggested or current-numbering boundary is shown on this page. Click a system to confirm a boundary manually before it.",
    suggested: "suggested {count}", confirmed: "confirmed {count}", checked: "checked-no-boundary {count}", movement: "movement",
    finishMovementRemaining: "Finish movement review ({count} suggestions left)", finishMovement: "Finish movement review",
    finishMovementHint: "Review every suggested boundary before finishing.", finishMovementDoneHint: "Create boundary data for the next numbering run. The displayed score will not change.",
    pageName: "Page {page}{name}", mmrRow: "System {system} · Measure {measure} | base={base} → effective={effective} | {status}",
    removedMmr: "Removed the manual multi-measure-rest correction for the selected measure.", baseLoadFailed: "Could not load the automatic multi-measure-rest result: {error}", movementLoadFailed: "Movement evidence load failed: {error}",
    noPages: "No pages configured.", noUnsaved: "There are no unsaved changes.", unsavedTypes: "Unsaved: {types}", systemPlaceholder: "e.g. 6", reasonDefault: "manual correction",
    selectedCount: "Change {number}", measureSpanLabel: "span {span}",
    movementSelection: "Movement target: Page {page} / System {system}{source} — boundary is before this system",
    measureSelection: "Page {page} / System {system} / Measure {measure} | base={base} effective={effective}",
    measureOverlay: "S{system} M{measure}", barlineIndex: "Barline {number}", targetLabel: "Target", draftLabel: "Draft", currentNumberingBoundary: "Boundary used by current numbering",
    movementCanvas: "{label}: before S{system}",
  },
  help: {pages: "Visible page, system, and measure numbers start at 1. Saved correction indices keep their existing format.", overlays: "Selected objects and active drafts remain visible when overlays are hidden. Barlines can be selected or drawn; other changes use the selected score target.", movement: "Movement decisions apply before the selected system. Movement decisions are saved immediately.", legendMeasure: "Measure", legendOriginal: "Original", legendRecorded: "Recorded change", legendSelected: "Selected"},
  noPageChanges: "No changes for this page and task.",
  clearDecision: "Clear recorded decision",
  result: {
    apply: "Generate corrected PDF", open: "Open corrected PDF",
    loading: "Result status is loading.", running: "Generating corrected PDF…",
    pending: "Record your edits before generating a corrected PDF.",
    stale: "The previous corrected PDF does not include the current corrections.",
    current: "The corrected PDF includes the recorded corrections.",
    ready: "Recorded corrections are ready to apply.",
    failure: "Corrected PDF needs attention", requestFailed: "Generation request failed",
  },
  state: {
    heading: "Correction status", pending: "unsaved", recorded: "recorded", errors: "errors", unavailable: "Correction status unavailable",
    page: "Page", source: "Source", result: "Corrected result",
    types: {mmr_measure_span: "Multi-measure rest", measure_construction: "Measure", barline_construction: "Barline", movement_boundary: "Movement boundary"},
    statuses: {none: "No unrecorded edit", pending: "Edit not recorded", not_recorded: "No correction recorded", recorded: "Correction recorded", not_applied: "No corrected result yet", current: "Corrected result is current", stale: "Recorded corrections changed since this result", applying: "Generating corrected result", error: "Needs attention", mixed: "Review has different correction states", package_mixed: "Review has different correction states"},
    requestFailed: "State request failed",
  },
  title: "Review correction",
  navigation: "Review result",
  page: "Page",
  previous: "Previous",
  next: "Next",
  selection: "Selected target",
  noSelection: "Select a measure, barline, or system on the score.",
  task: "Correction task",
  taskType: "Correction type",
  types: { mmr_measure_span: "Multi-measure rest", barline_construction: "Barline", measure_construction: "Measure", movement_boundary: "Movement boundary" },
  measureSpan: "Number of measures in rest",
  targetSystem: "Target system",
  reason: "Reason",
  currentChanges: "Current page changes",
  finishMovement: "Finish movement review",
  operation: "Change",
  operations: {
    mmr_measure_span: [["set_measure_span", "Set rest measure count"], ["suppress", "Do not treat as multi-measure rest"]],
    barline_construction: [["remove_barline", "Remove barline"], ["add_barline", "Add barline"]],
    measure_construction: [["force_measure", "Add measure"]],
    movement_boundary: [["boundary", "Confirm boundary before system"], ["no_boundary", "Confirm no boundary here"]],
  },
  select: "Select target",
  draw: "Draw barline",
  stage: "Add change",
  remove: "Remove change",
  save: "Save changes",
  saved: "Changes saved.",
  noChanges: "There are no unsaved changes.",
  feedback: {
    selectMeasure: "Select a measure on the score first.",
    invalidSpan: "Enter a measure span of 1 or more.",
    draftAdded: "Draft added. Save changes to record it.",
    stagedSpan: "Draft: multi-measure-rest count",
    stagedSuppression: "Draft: multi-measure-rest correction removed",
    invalidSystem: "Enter a valid system number.",
    missingSystem: "System {system} is not on this page.",
    noSuggestion: "There is no suggested boundary here to dismiss.",
    savingBoundary: "Saving boundary before system {system}…",
    savingNoBoundary: "Saving no-boundary decision before system {system}…",
    savedBoundary: "Boundary before system {system} saved.",
    savedNoBoundary: "No-boundary decision before system {system} saved.",
    selectBarline: "Select a barline or draw one on the score.",
    selectInterval: "Select a measure interval on the score first.",
    removedDraft: "Draft removed.",
    removingDecision: "Removing saved decision…",
    clearedDecision: "Saved decision removed.",
    pageMovement: "This page: {existing} current boundaries · {confirmed} confirmed · {checked} checked with no boundary · {suggestions} suggestions",
    finishBlocked: "Review the remaining {count} boundary suggestions before finishing.",
    finishMovement: "Movement review finished. {count} confirmed boundaries are ready for the next numbering run.",
    finishMovementFailed: "Could not finish movement review: {error}",
    movementSaveFailed: "Could not save movement decision: {error}",
    saveFailed: "Could not save changes: {error}",
    pageEditedDuringSave: "New edits remain unsaved. Save them before changing page.",
    pageSaveFailed: "Page change stopped because saving failed: {error}",
  },
  status: "Correction status",
  editStatus: "Editing",
  recordingStatus: "Saved changes",
  applicationStatus: "Result status",
  apply: "Apply changes",
  openResult: "Open corrected result",
  details: "Details and evidence",
  display: "Score display",
  measures: "Measures",
  barlines: "Barlines",
  labels: "Labels",
  baseState: "Original grouping",
  manualState: "Your changes",
  movement: "Movement boundaries",
  canvasHint: "Scroll to zoom · Space-drag or middle-drag to pan · ←/→ changes page",
  stateLoading: "Loading correction status…",
  stateUnavailable: "Correction status is not available yet.",
  unsaved: "Changes not saved",
  empty: "No correction selected",
};

const reviewJapanese = {
  language: "言語",
  aria: {language: "表示言語", pages: "結果ページ", display: "楽譜の表示", canvas: "楽譜確認キャンバス"},
  ui: {
    change: "修正", page: "ページ", system: "段", measure: "小節", span: "小節数", bbox: "領域", draft: "修正案",
    unsaved: "未保存", confirmBoundary: "この段の前を楽章境界にする", confirmNoBoundary: "ここに楽章境界を設けない",
    noSystem: "対象の段が選択されていません。対象の段をクリックするか、段番号を入力してください。",
    movementPrompt: "楽章境界を確認する段を選択してください。", noSystemSelected: "段が選択されていません。",
    selectedMeasure: "小節 {measure} から段を特定しました。小節自体は対象ではありません。",
    currentState: "現在の状態：{state}。", noBoundaryState: "現在の状態：境界候補または確定済み境界はありません。",
    targetBefore: "対象：段 {system}。この段の前に楽章境界を設定します。",
    missingSystem: "このページに段 {system} はありません。",
    movementCounts: "このページ：現在の番号付けの境界 {existing} 件・確定 {confirmed} 件・境界なし {checked} 件・未確認候補 {suggestions} 件",
    target: "対象", before: "の前", selectedBarline: "選択中の小節線", normal: "複数小節休符なし", baseMmr: "自動判定：複数小節休符",
    noMeasures: "番号付けデータから小節領域を読み込めませんでした。", movementGuide: "以下の位置はすべて段 N の前を示します。行をクリックすると楽譜上の段を選択できます。",
    confirmedBoundary: "境界として確定", manualBoundary: "境界として確定（手動）", checkedNoBoundary: "確認済み：境界なし",
    resolvedBoundary: "現在の番号付けで使用中の境界 · 番号を {reset} にリセット", suggestedBoundary: "境界候補 — 確認が必要",
    beforeSystem: "段 {system} の前 · {state}", detectionDetails: "検出の詳細",
    noBoundaryRows: "このページに候補または現在の番号付けで使われる境界はありません。段をクリックすると、その前に境界を手動で設定できます。",
    suggested: "候補 {count} 件", confirmed: "確定 {count} 件", checked: "境界なし {count} 件", movement: "楽章境界",
    finishMovementRemaining: "楽章境界の確認を完了（残り候補 {count} 件）", finishMovement: "楽章境界の確認を完了",
    finishMovementHint: "完了する前にすべての境界候補を確認してください。", finishMovementDoneHint: "次回の番号付けに使う境界データを作成します。表示中の楽譜は変わりません。",
    pageName: "ページ {page}{name}", mmrRow: "段 {system} · 小節 {measure} | 元={base} → 適用後={effective} | {status}",
    removedMmr: "選択した小節の複数小節休符に関する手動修正を削除しました。", baseLoadFailed: "複数小節休符の自動判定結果を読み込めませんでした：{error}", movementLoadFailed: "楽章境界の根拠を読み込めませんでした：{error}",
    noPages: "ページが設定されていません。", noUnsaved: "未保存の変更はありません。", unsavedTypes: "未保存：{types}", systemPlaceholder: "例：6", reasonDefault: "手動修正",
    selectedCount: "修正 {number}", measureSpanLabel: "小節数 {span}",
    movementSelection: "楽章境界の対象：ページ {page} / 段 {system}{source} — 境界はこの段の前に設定",
    measureSelection: "ページ {page} / 段 {system} / 小節 {measure} | 元={base} 適用後={effective}",
    measureOverlay: "段{system} 小節{measure}", barlineIndex: "小節線 {number}", targetLabel: "対象", draftLabel: "修正案", currentNumberingBoundary: "現在の番号付けで使用中の境界",
    movementCanvas: "{label}：段{system}の前",
  },
  help: {pages: "画面上のページ・段・小節番号は1から始まります。保存される修正インデックスの形式は変わりません。", overlays: "重ね表示を隠しても、選択中の対象や編集中の修正案は表示されます。小節線は選択または描画でき、その他の修正は楽譜上で選択した対象を使います。", movement: "楽章境界の判断は選択した段の前に適用され、判断はすぐに保存されます。", legendMeasure: "小節", legendOriginal: "元の状態", legendRecorded: "記録した修正", legendSelected: "選択中"},
  noPageChanges: "このページと作業には変更がありません。", clearDecision: "記録した判断を解除",
  result: {
    apply: "修正済みPDFを生成", open: "修正済みPDFを開く", loading: "修正済みPDFの状態を確認しています…", running: "修正済みPDFを生成中…",
    pending: "修正済みPDFを生成する前に、編集内容を保存してください。",
    stale: "前回の修正済みPDFには現在の修正が反映されていません。",
    current: "修正済みPDFには記録済みの修正が反映されています。",
    ready: "記録済みの修正を適用できます。", failure: "修正済みPDFの確認が必要です。",
    requestFailed: "生成リクエストに失敗しました。",
  },
  state: {
    heading: "修正状況", pending: "未保存", recorded: "記録済み", errors: "エラー",
    unavailable: "修正状況を取得できません。", page: "ページ", source: "元の結果", result: "修正済み結果",
    types: {mmr_measure_span: "複数小節休符（MMR）", measure_construction: "小節", barline_construction: "小節線", movement_boundary: "楽章境界"},
    statuses: {none: "未記録の編集なし", pending: "編集が未記録", not_recorded: "修正の記録なし", recorded: "修正を記録済み", not_applied: "修正済み結果は未生成", current: "修正済み結果は最新", stale: "記録後に修正内容が変更されました", applying: "修正済み結果を生成中", error: "要確認", mixed: "修正状態を確認", package_mixed: "修正状態を確認"},
    requestFailed: "修正状態の取得に失敗しました。",
  },
  title: "結果を確認・修正", navigation: "結果の確認", page: "ページ", previous: "前へ", next: "次へ",
  selection: "選択中の対象", noSelection: "楽譜上の小節、小節線、または段を選択してください。",
  task: "修正内容", taskType: "修正の種類",
  types: {mmr_measure_span: "複数小節休符（MMR）", barline_construction: "小節線", measure_construction: "小節", movement_boundary: "楽章境界"},
  measureSpan: "複数小節休符の小節数", targetSystem: "対象の段", reason: "理由", currentChanges: "このページの修正",
  finishMovement: "楽章境界の確認を完了", operation: "操作",
  operations: {
    mmr_measure_span: [["set_measure_span", "複数小節休符の小節数を設定"], ["suppress", "複数小節休符として扱わない"]],
    barline_construction: [["remove_barline", "小節線を削除"], ["add_barline", "小節線を追加"]],
    measure_construction: [["force_measure", "小節を追加"]],
    movement_boundary: [["boundary", "この段の前を楽章境界にする"], ["no_boundary", "ここに楽章境界を設けない"]],
  },
  select: "対象を選択", draw: "小節線を描画", stage: "修正を追加", remove: "修正を削除",
  save: "変更を保存", saved: "変更を保存しました。", noChanges: "保存する変更はありません。",
  feedback: {
    selectMeasure: "先に楽譜上の小節を選択してください。", invalidSpan: "小節数は1以上を入力してください。",
    draftAdded: "修正案を追加しました。記録するには変更を保存してください。", stagedSpan: "修正案：小節数",
    stagedSuppression: "修正案：複数小節休符として扱わない", invalidSystem: "有効な段番号を入力してください。",
    missingSystem: "このページに段 {system} はありません。", noSuggestion: "ここに解除できる境界候補はありません。",
    savingBoundary: "段 {system} の前を楽章境界として保存中…", savingNoBoundary: "段 {system} の前に境界を設けない判断を保存中…",
    savedBoundary: "段 {system} の前を楽章境界として保存しました。", savedNoBoundary: "段 {system} の前に境界を設けない判断を保存しました。",
    selectBarline: "小節線を選択するか、楽譜上に描画してください。", selectInterval: "先に楽譜上の小節範囲を選択してください。",
    removedDraft: "修正案を削除しました。", removingDecision: "保存した判断を削除中…", clearedDecision: "保存した判断を削除しました。",
    pageMovement: "このページ：境界 {existing} 件・確定 {confirmed} 件・境界なし {checked} 件・候補 {suggestions} 件",
    finishBlocked: "完了する前に、残り {count} 件の境界候補を確認してください。",
    finishMovement: "楽章境界の確認が完了しました。{count} 件の境界を次回の番号付けに適用できます。",
    finishMovementFailed: "楽章境界の確認を完了できませんでした：{error}", movementSaveFailed: "楽章境界の判断を保存できませんでした：{error}",
    saveFailed: "変更を保存できませんでした：{error}", pageEditedDuringSave: "新しい編集が未保存です。ページを移動する前に保存してください。",
    pageSaveFailed: "保存に失敗したためページを移動できませんでした：{error}",
  },
  status: "修正状況", editStatus: "編集中", recordingStatus: "保存した変更", applicationStatus: "結果の状態",
  apply: "変更を適用", openResult: "修正済み結果を開く", details: "詳細と根拠", display: "楽譜の表示",
  measures: "小節", barlines: "小節線", labels: "番号", baseState: "元の複数小節休符判定", manualState: "修正内容",
  movement: "楽章境界", canvasHint: "スクロールで拡大・縮小 · Spaceキー＋ドラッグまたは中ボタンドラッグで移動 · ←/→でページ移動",
  stateLoading: "修正状況を読み込み中…", stateUnavailable: "修正状況をまだ取得できません。",
  unsaved: "未保存の変更", empty: "修正対象が選択されていません。",
};

window.ReviewStringCatalogs = Object.freeze({en: Object.freeze(reviewEnglish), ja: Object.freeze(reviewJapanese)});
window.ReviewStrings = window.ReviewStringCatalogs.en;
