baseline_dataset_root: datasets/cnn_classifier_v1_issue44_hcfn_iter1
hard_positive_dir: logs/cnn_barline_classification/issue44_hcfn_iter3/mining_from_iter2_th0p1/hard_positives
output_dataset_root: datasets/cnn_classifier_v1_issue44_hcfn_iter3

split: train
copy_mode: hardlink
name_prefix: issue44_hcfn_iter3
dedup: true
